### ISSUE TITLE
 Checklist

### ISSUE THREAD

**Issue by fergodani** [fergodani/Juego2D#1]
# TO DO
## Funcionalidades

- [x] Movimiento y animaciones personaje
- [x] Acción de las herramientas
- [x] Recolectar semillas
- [x] Recolectar madera
- [x] Recolectar piedra (falta obtenerla en el inventario)
- [x] Arado
- [x] Regado
- [x] Recolectar cultivo
- [x] Ciclo de cultivo
- [x] Inventario
- [x] Poder seleccionar algo y ponerlo en el suelo
- [x] Tienda (crafteo)
- [x] Aspersor
- [x] Recolector automático
- [x] Hacer menú de inicio
- [x] Añadir sonidos
- [x] Balancear el juego
- [x] Poder limpiar las tiles (si hay algo encima como un cultivo quitarlo, o un item)

## Defectos

- [x] Parar al personaje mientras se haga las animaciones de las herramientas
- [x] Generación correcta de semillas, madera y piedra
- [x] Esperar a que acabe la animación para hacer la acción (ahora solo se recogen una vez acaba, queda raro. Si no es posible dejarlo así)
- [x] Añadir los detalles a las GroundTile.
- [x] Tener en cuenta la orientación del personaje al arar, regar...
- [x] Si dejas pulsado el botón action se buguea porque se activa muchas veces seguidas. (solucionado menos en los árboles)
- [x] Hacer que el inventario dibuje el hud, no el gameLayer.
- [x] Mejorar dibujado del recolector y mejorar sprite aspersor.
- [x] Mejorar el menú de inicio. Ahora es muy cutre.
- [x] Solo deja comprar una vez.
- [x] Números de dos cifras en el hud raros.
- [x] Corregir generación dentro del crafteo.
- [x] Si se genera algo en una esquina no se puede coger.
